name: etl-pipeline-network-placeholder

networks:
  etl-network:
    name: etl-network
    driver: bridge

services:
  etl-gateway:
    image: nginx:alpine
    container_name: etl-gateway
    restart: unless-stopped
    networks:
      - etl-network
