name: etl-pipeline

networks:
  etl-network:
    name: etl-network
    external: true

services:
  etl-dozzle:
    image: amir20/dozzle:v10
    container_name: etl-dozzle
    restart: unless-stopped
    networks:
      - etl-network
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOZZLE_FILTER: "name=etl-"

  etl-kafka:
    image: confluentinc/cp-kafka:8.1.2
    container_name: etl-kafka
    restart: unless-stopped
    networks:
      - etl-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://etl-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@etl-kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  etl-kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.4.2
    container_name: etl-kafka-ui
    restart: unless-stopped
    networks:
      - etl-network
    ports:
      - "8889:8080"
    depends_on:
      etl-kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: etl-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: etl-kafka:9092
