events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Kafka UI REST API
        location /api/kafka/ {
            proxy_pass http://etl-kafka-ui:8080/;
            proxy_set_header Host etl-kafka-ui:8080;
            proxy_set_header X-Real-IP $remote_addr;
            add_header Access-Control-Allow-Origin *;
        }

        # Elasticsearch
        location /api/elastic/ {
            proxy_pass http://etl-elasticsearch:9200/;
            proxy_set_header Host etl-elasticsearch:9200;
            add_header Access-Control-Allow-Origin *;
        }

        # HDFS NameNode JMX
        location /api/hdfs/ {
            proxy_pass http://etl-namenode:9870/;
            proxy_set_header Host etl-namenode:9870;
            add_header Access-Control-Allow-Origin *;
        }

        # Cassandra Web UI health check
        location /api/cassandra/ {
            proxy_pass http://etl-cassandra:9042/;
            proxy_set_header Host etl-cassandra;
            add_header Access-Control-Allow-Origin *;
        }
    }
}
