events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /api/kb/ {
            proxy_pass http://svcb3x:8080/;
            proxy_set_header Host svcb3x:8080;
            proxy_set_header X-Real-IP $remote_addr;
            add_header Access-Control-Allow-Origin *;
        }

        location /api/se/ {
            proxy_pass http://svcf1:9200/;
            proxy_set_header Host svcf1:9200;
            add_header Access-Control-Allow-Origin *;
        }

        location /api/fs/ {
            proxy_pass http://ndx00:9870/;
            proxy_set_header Host ndx00:9870;
            add_header Access-Control-Allow-Origin *;
        }

        location /api/store/ {
            proxy_pass http://svcd7:9042/;
            proxy_set_header Host svcd7;
            add_header Access-Control-Allow-Origin *;
        }
    }
}
